server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    #Allowing CORS (Cross-Origin Resource Sharing) by adding the Access-Control-Allow-Origin header to font files
    location ~* \.(eot|ttf|woff|woff2)$ {
        add_header Access-Control-Allow-Origin *;
        add_header Access-Control-Allow-Methods "GET, POST, DELETE, OPTIONS";
        add_header Access-Control-Allow-Headers "DNT,User-Agent,Cache-Control,Content-Type,Authorization";

    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass http://backend-service:80/;
    }

}